  [FORCE_GRAVITATIONNELLE FORCE_FROTTEMENT_VISQUEUX FORCE_MAGNUS] = Calculs_Forces(MASSE_BALLON,RAYON_BALLON,AIR_BALLON,Z_FORCE_GRAVITATIONNELLE,MASSE_VOLUMIQUE_AIR,VISCOSITE_AIR,VITESSE,VITESSE_ANGULAIRE)

  FORCE_GRAVITATIONNELLE = [0;0;Z_FORCE_GRAVITATIONNELLE];
  
  %CALCULS POUR FORCE_FROTTEMENT_VISQUEUX %
  
  %1: Calcul du coefficient de trainee visqueuese
    COEFFICIENT_TRAINEE =0;
    NORME_VITESSE = norm(VITESSE)
    NOMBRE_DE_REYNOLDS = (NORME_VITESSE*MASSE_VOLUMIQUE_AIR*RAYON_BALLON)/VISCOSITE_AIR;
    
    %Definition des cas possibles pour le coefficient
    
     if(NOMBRE_DE_REYNOLDS<100000)
      COEFFICIENT_TRAINEE = NORME_VITESSE*0.235;
     elseif(NOMBRE_DE_REYNOLDS<135000 && NOMBRE_DE_REYNOLDS>100000)
      COEFFICIENT_TRAINEE = (NORME_VITESSE*0.235) - NORME_VITESSE*0.125*((NOMBRE_DE_REYNOLDS-100000)/35000);
     else
      COEFFICIENT_TRAINEE = NORME_VITESSE*0.110;
     end
     %Obtention de la valeur de FORCE_FROTTEMENT_VISQUEUX
     
     FORCE_FROTTEMENT_VISQUEUX = -AIR_BALLON*MASSE_VOLUMIQUE_AIR*COEFFICIENT_TRAINEE*VITESSE;
     
     
    %CALCUL POUR FORCE_MAGNUS%
    
    %1 Calcul du coefficient de magnus%
    
    COEFFICIENT_MAGNUS = 0.1925 * ((norm(VITESSE_ANGULAIRE)*RAYON_BALLON)/NORME_VITESSE).^(1/4) %.^ c'est comme pow(x,y)%
     
     %Calcul de la valeur de la force
     
     PRODUIT_VECTEURS = cross(VITESSE,VITESSE_ANGULAIRE);
     
     NORME_PRODUIT_VECTEURS= norm(PRODUIT_VECTEURS);
     
     FORCE_MAGNUS = MASSE_VOLUMIQUE_AIR* COEFFICIENT_MAGNUS* AIR_BALLON* NORME_VITESSE^2 * (PRODUIT_VECTEURS/NORME_PRODUIT_VECTEURS);
     
     
   
    
  
  
